# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import points_service_pb2 as vortex_dot_api_dot_v1_dot_points__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vortex/api/v1/points_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PointsServiceStub(object):
    """Service for managing points (vectors and their payloads).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertPoints = channel.unary_unary(
                '/vortex.api.v1.PointsService/UpsertPoints',
                request_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.UpsertPointsRequest.SerializeToString,
                response_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.UpsertPointsResponse.FromString,
                _registered_method=True)
        self.GetPoints = channel.unary_unary(
                '/vortex.api.v1.PointsService/GetPoints',
                request_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.GetPointsRequest.SerializeToString,
                response_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.GetPointsResponse.FromString,
                _registered_method=True)
        self.DeletePoints = channel.unary_unary(
                '/vortex.api.v1.PointsService/DeletePoints',
                request_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.DeletePointsRequest.SerializeToString,
                response_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.DeletePointsResponse.FromString,
                _registered_method=True)
        self.SearchPoints = channel.unary_unary(
                '/vortex.api.v1.PointsService/SearchPoints',
                request_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.SearchPointsRequest.SerializeToString,
                response_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.SearchPointsResponse.FromString,
                _registered_method=True)


class PointsServiceServicer(object):
    """Service for managing points (vectors and their payloads).
    """

    def UpsertPoints(self, request, context):
        """Upserts (adds or updates) points in a collection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoints(self, request, context):
        """Retrieves points by their IDs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePoints(self, request, context):
        """Deletes points from a collection by their IDs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPoints(self, request, context):
        """Performs a k-NN search for similar points.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertPoints,
                    request_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.UpsertPointsRequest.FromString,
                    response_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.UpsertPointsResponse.SerializeToString,
            ),
            'GetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoints,
                    request_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.GetPointsRequest.FromString,
                    response_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.GetPointsResponse.SerializeToString,
            ),
            'DeletePoints': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePoints,
                    request_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.DeletePointsRequest.FromString,
                    response_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.DeletePointsResponse.SerializeToString,
            ),
            'SearchPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPoints,
                    request_deserializer=vortex_dot_api_dot_v1_dot_points__service__pb2.SearchPointsRequest.FromString,
                    response_serializer=vortex_dot_api_dot_v1_dot_points__service__pb2.SearchPointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vortex.api.v1.PointsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vortex.api.v1.PointsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PointsService(object):
    """Service for managing points (vectors and their payloads).
    """

    @staticmethod
    def UpsertPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vortex.api.v1.PointsService/UpsertPoints',
            vortex_dot_api_dot_v1_dot_points__service__pb2.UpsertPointsRequest.SerializeToString,
            vortex_dot_api_dot_v1_dot_points__service__pb2.UpsertPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vortex.api.v1.PointsService/GetPoints',
            vortex_dot_api_dot_v1_dot_points__service__pb2.GetPointsRequest.SerializeToString,
            vortex_dot_api_dot_v1_dot_points__service__pb2.GetPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vortex.api.v1.PointsService/DeletePoints',
            vortex_dot_api_dot_v1_dot_points__service__pb2.DeletePointsRequest.SerializeToString,
            vortex_dot_api_dot_v1_dot_points__service__pb2.DeletePointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vortex.api.v1.PointsService/SearchPoints',
            vortex_dot_api_dot_v1_dot_points__service__pb2.SearchPointsRequest.SerializeToString,
            vortex_dot_api_dot_v1_dot_points__service__pb2.SearchPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
